version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
            
  package-publisher:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: mkdir ~/.npm-global && npm config set prefix '~/.npm-global' && export PATH=~/.npm-global/bin:$PATH && source ~/.profile
      - run: npm install lerna@1
      - run: lerna publish --canary --preid next
#      - run: npm adduser --registry=http://private-registry.example.com --always-auth

workflows:
  test:
    jobs:
      - build-and-test:
          filters:
            tags:

      - package-publisher:
          requires:
            - build-and-test
          filters:
            tags:

