version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:coverage
            
#  package-publisher:
#    executor:
#      name: node/default
#    steps:
#     - checkout
#     - node/with-cache:
#         steps:
#           - run: npm install -g --publisher--
#           - run: publish-script -t ${CI_BUILD_TAG}
workflows:
    build-and-test:
      jobs:
        - build-and-test
