version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
            
  package-publisher:
    executor:
      name: node/default
    steps:
     - checkout
     - node/with-cache:
         steps:
           - run: mkdir ~/.npm-global && npm config set prefix '~/.npm-global' && export PATH=~/.npm-global/bin:$PATH && source ~/.profile
           - run: npm install -g
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - package-publisher
