version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
   filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
            
  package-publisher:
   filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.15.3
    steps:
     - checkout
     - node/with-cache:
         steps:
           - run: mkdir ~/.npm-global && npm config set prefix '~/.npm-global' && export PATH=~/.npm-global/bin:$PATH && source ~/.profile
           - run: npm install -g my-test-package
#           - run: npm adduser --registry=http://private-registry.example.com --always-auth
#           - run: npm publish my-test-package
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - package-publisher:
            requires:
              - build-and-test

